# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: air_cond.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='air_cond.proto',
  package='MyPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61ir_cond.proto\x12\tMyPackage\x1a\x1bgoogle/protobuf/empty.proto\"p\n\x0c\x41irCondState\x12,\n\x05state\x18\x01 \x01(\x0e\x32\x1d.MyPackage.AirCondState.State\"2\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x08\n\x04WEAK\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\n\n\x06STRONG\x10\x03\x32\x87\x01\n\x07\x41irCond\x12=\n\x08getState\x12\x16.google.protobuf.Empty\x1a\x17.MyPackage.AirCondState\"\x00\x12=\n\x08setState\x12\x17.MyPackage.AirCondState\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_AIRCONDSTATE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='MyPackage.AirCondState.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEAK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STRONG', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=120,
  serialized_end=170,
)
_sym_db.RegisterEnumDescriptor(_AIRCONDSTATE_STATE)


_AIRCONDSTATE = _descriptor.Descriptor(
  name='AirCondState',
  full_name='MyPackage.AirCondState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='MyPackage.AirCondState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AIRCONDSTATE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=170,
)

_AIRCONDSTATE.fields_by_name['state'].enum_type = _AIRCONDSTATE_STATE
_AIRCONDSTATE_STATE.containing_type = _AIRCONDSTATE
DESCRIPTOR.message_types_by_name['AirCondState'] = _AIRCONDSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AirCondState = _reflection.GeneratedProtocolMessageType('AirCondState', (_message.Message,), {
  'DESCRIPTOR' : _AIRCONDSTATE,
  '__module__' : 'air_cond_pb2'
  # @@protoc_insertion_point(class_scope:MyPackage.AirCondState)
  })
_sym_db.RegisterMessage(AirCondState)



_AIRCOND = _descriptor.ServiceDescriptor(
  name='AirCond',
  full_name='MyPackage.AirCond',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=173,
  serialized_end=308,
  methods=[
  _descriptor.MethodDescriptor(
    name='getState',
    full_name='MyPackage.AirCond.getState',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_AIRCONDSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setState',
    full_name='MyPackage.AirCond.setState',
    index=1,
    containing_service=None,
    input_type=_AIRCONDSTATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRCOND)

DESCRIPTOR.services_by_name['AirCond'] = _AIRCOND

# @@protoc_insertion_point(module_scope)
