# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lamp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lamp.proto',
  package='MyPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nlamp.proto\x12\tMyPackage\x1a\x1bgoogle/protobuf/empty.proto\"P\n\tLampState\x12)\n\x05state\x18\x01 \x01(\x0e\x32\x1a.MyPackage.LampState.State\"\x18\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x32~\n\x04Lamp\x12:\n\x08getState\x12\x16.google.protobuf.Empty\x1a\x14.MyPackage.LampState\"\x00\x12:\n\x08setState\x12\x14.MyPackage.LampState\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_LAMPSTATE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='MyPackage.LampState.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=110,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_LAMPSTATE_STATE)


_LAMPSTATE = _descriptor.Descriptor(
  name='LampState',
  full_name='MyPackage.LampState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='MyPackage.LampState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAMPSTATE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=134,
)

_LAMPSTATE.fields_by_name['state'].enum_type = _LAMPSTATE_STATE
_LAMPSTATE_STATE.containing_type = _LAMPSTATE
DESCRIPTOR.message_types_by_name['LampState'] = _LAMPSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LampState = _reflection.GeneratedProtocolMessageType('LampState', (_message.Message,), {
  'DESCRIPTOR' : _LAMPSTATE,
  '__module__' : 'lamp_pb2'
  # @@protoc_insertion_point(class_scope:MyPackage.LampState)
  })
_sym_db.RegisterMessage(LampState)



_LAMP = _descriptor.ServiceDescriptor(
  name='Lamp',
  full_name='MyPackage.Lamp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=136,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='getState',
    full_name='MyPackage.Lamp.getState',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LAMPSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setState',
    full_name='MyPackage.Lamp.setState',
    index=1,
    containing_service=None,
    input_type=_LAMPSTATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAMP)

DESCRIPTOR.services_by_name['Lamp'] = _LAMP

# @@protoc_insertion_point(module_scope)
