# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measure.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='measure.proto',
  package='messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmeasure.proto\x12\x08messages\"\x18\n\x07Measure\x12\r\n\x05value\x18\x01 \x01(\x02\x62\x06proto3')
)




_MEASURE = _descriptor.Descriptor(
  name='Measure',
  full_name='messages.Measure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='messages.Measure.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Measure'] = _MEASURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Measure = _reflection.GeneratedProtocolMessageType('Measure', (_message.Message,), dict(
  DESCRIPTOR = _MEASURE,
  __module__ = 'measure_pb2'
  # @@protoc_insertion_point(class_scope:messages.Measure)
  ))
_sym_db.RegisterMessage(Measure)


# @@protoc_insertion_point(module_scope)
