# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watering_can.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='watering_can.proto',
  package='MyPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12watering_can.proto\x12\tMyPackage\x1a\x1bgoogle/protobuf/empty.proto\"^\n\x10WateringCanState\x12\x30\n\x05state\x18\x01 \x01(\x0e\x32!.MyPackage.WateringCanState.State\"\x18\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x32\x93\x01\n\x0bWateringCan\x12\x41\n\x08getState\x12\x16.google.protobuf.Empty\x1a\x1b.MyPackage.WateringCanState\"\x00\x12\x41\n\x08setState\x12\x1b.MyPackage.WateringCanState\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_WATERINGCANSTATE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='MyPackage.WateringCanState.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=156,
)
_sym_db.RegisterEnumDescriptor(_WATERINGCANSTATE_STATE)


_WATERINGCANSTATE = _descriptor.Descriptor(
  name='WateringCanState',
  full_name='MyPackage.WateringCanState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='MyPackage.WateringCanState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WATERINGCANSTATE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=156,
)

_WATERINGCANSTATE.fields_by_name['state'].enum_type = _WATERINGCANSTATE_STATE
_WATERINGCANSTATE_STATE.containing_type = _WATERINGCANSTATE
DESCRIPTOR.message_types_by_name['WateringCanState'] = _WATERINGCANSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WateringCanState = _reflection.GeneratedProtocolMessageType('WateringCanState', (_message.Message,), {
  'DESCRIPTOR' : _WATERINGCANSTATE,
  '__module__' : 'watering_can_pb2'
  # @@protoc_insertion_point(class_scope:MyPackage.WateringCanState)
  })
_sym_db.RegisterMessage(WateringCanState)



_WATERINGCAN = _descriptor.ServiceDescriptor(
  name='WateringCan',
  full_name='MyPackage.WateringCan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=159,
  serialized_end=306,
  methods=[
  _descriptor.MethodDescriptor(
    name='getState',
    full_name='MyPackage.WateringCan.getState',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_WATERINGCANSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setState',
    full_name='MyPackage.WateringCan.setState',
    index=1,
    containing_service=None,
    input_type=_WATERINGCANSTATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WATERINGCAN)

DESCRIPTOR.services_by_name['WateringCan'] = _WATERINGCAN

# @@protoc_insertion_point(module_scope)
