# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ar_cond.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ar_cond.proto',
  package='arCond',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rar_cond.proto\x12\x06\x61rCond\"\x1e\n\rArCondRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\x0b\x41rCondReply\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\rServiceArCond\x12<\n\x0cTurnOnArCond\x12\x15.arCond.ArCondRequest\x1a\x13.arCond.ArCondReply\"\x00\x62\x06proto3'
)




_ARCONDREQUEST = _descriptor.Descriptor(
  name='ArCondRequest',
  full_name='arCond.ArCondRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='arCond.ArCondRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=55,
)


_ARCONDREPLY = _descriptor.Descriptor(
  name='ArCondReply',
  full_name='arCond.ArCondReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='arCond.ArCondReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['ArCondRequest'] = _ARCONDREQUEST
DESCRIPTOR.message_types_by_name['ArCondReply'] = _ARCONDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArCondRequest = _reflection.GeneratedProtocolMessageType('ArCondRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARCONDREQUEST,
  '__module__' : 'ar_cond_pb2'
  # @@protoc_insertion_point(class_scope:arCond.ArCondRequest)
  })
_sym_db.RegisterMessage(ArCondRequest)

ArCondReply = _reflection.GeneratedProtocolMessageType('ArCondReply', (_message.Message,), {
  'DESCRIPTOR' : _ARCONDREPLY,
  '__module__' : 'ar_cond_pb2'
  # @@protoc_insertion_point(class_scope:arCond.ArCondReply)
  })
_sym_db.RegisterMessage(ArCondReply)



_SERVICEARCOND = _descriptor.ServiceDescriptor(
  name='ServiceArCond',
  full_name='arCond.ServiceArCond',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=89,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='TurnOnArCond',
    full_name='arCond.ServiceArCond.TurnOnArCond',
    index=0,
    containing_service=None,
    input_type=_ARCONDREQUEST,
    output_type=_ARCONDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICEARCOND)

DESCRIPTOR.services_by_name['ServiceArCond'] = _SERVICEARCOND

# @@protoc_insertion_point(module_scope)
