# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ar_cond_pb2 as ar__cond__pb2


class ServiceArCondStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TurnOnArCond = channel.unary_unary(
                '/arCond.ServiceArCond/TurnOnArCond',
                request_serializer=ar__cond__pb2.ArCondRequest.SerializeToString,
                response_deserializer=ar__cond__pb2.ArCondReply.FromString,
                )


class ServiceArCondServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TurnOnArCond(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceArCondServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TurnOnArCond': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOnArCond,
                    request_deserializer=ar__cond__pb2.ArCondRequest.FromString,
                    response_serializer=ar__cond__pb2.ArCondReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arCond.ServiceArCond', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceArCond(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TurnOnArCond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arCond.ServiceArCond/TurnOnArCond',
            ar__cond__pb2.ArCondRequest.SerializeToString,
            ar__cond__pb2.ArCondReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
